services:
  backend:
    image: ghcr.io/5-logic/the-sync-backend:latest
    container_name: the-sync-backend
    env_file:
      - .backend.env
    labels:
      - "diun.enable=true"
    networks:
      - the-sync-network

  proxy:
    image: nginx:alpine
    container_name: proxy
    restart: unless-stopped
    ports:
      - 4000:4000
      - 9000:9000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/[yourdomain]:/etc/ssl:ro
    depends_on:
      - backend
      - portainer
    networks:
      - the-sync-network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - the-sync-network

  diun:
    image: crazymax/diun:latest
    container_name: diun
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - diun_data:/data
    env_file:
      - .diun.env
    environment:
      - TZ=UTC
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=10
      - DIUN_WATCH_SCHEDULE=*/10 * * * *
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=false
      - DIUN_NOTIF_DISCORD_MENTIONS=@everyone
      - DIUN_NOTIF_DISCORD_TIMEOUT=10s
    labels:
      - "diun.enable=true"
    networks:
      - the-sync-network

networks:
  the-sync-network:
    driver: bridge

volumes:
  portainer_data:
  diun_data:

name: the-sync
