services:
  backend:
    image: ghcr.io/5-logic/the-sync-backend:latest
    container_name: the-sync-backend
    ports:
      - 4000:4000
    env_file:
      - .backend.env
    networks:
      - the-sync-network

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 81:81
    environment:
      DISABLE_IPV6: true
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - the-sync-network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - the-sync-network

networks:
  the-sync-network:
    driver: bridge

volumes:
  npm_data:
  npm_letsencrypt:
  portainer_data:

name: the-sync